/**
 * Tenon — 数据灌入脚本
 *
 * 读 src/content/posts/ 的 Markdown 文件，解析 frontmatter，
 * 生成 SQL INSERT 语句灌入 D1 tenon_contents。
 *
 * 用法：
 *   node scripts/import-to-d1.js > import.sql
 *   npx wrangler d1 execute tenon-db --remote --file=import.sql
 */

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const POSTS_DIR = path.resolve(__dirname, "../src/content/posts");
const MODULE_ID = "mod_posts"; // 对应 0001_init.sql 里的 posts module

/**
 * 解析 YAML-like frontmatter，返回 { data, body }
 */
function parseFrontmatter(content) {
	const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
	if (!match) {
		return { data: {}, body: content.trim() };
	}

	const frontmatterStr = match[1];
	const body = match[2].trim();

	const data = {};
	const lines = frontmatterStr.split("\n");
	for (const line of lines) {
		const colonIdx = line.indexOf(":");
		if (colonIdx === -1) continue;

		const key = line.substring(0, colonIdx).trim();
		let value = line.substring(colonIdx + 1).trim();

		// 解析数组 [item1, item2]
			if (value.startsWith("[") && value.endsWith("]")) {
				value = value
					.slice(1, -1)
					.split(",")
					.map((s) => {
						s = s.trim();
						// 去掉元素外层引号
						if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
							s = s.slice(1, -1);
						}
						return s;
					})
					.filter(Boolean);
			}
		// 管 try 解析布尔值、空字符串
		else if (value === "true" || value === "false") {
			value = value === "true";
		}
		// 去掉引号
		else if (
			(value.startsWith('"') && value.endsWith('"')) ||
			(value.startsWith("'") && value.endsWith("'"))
		) {
			value = value.slice(1, -1);
		}

		data[key] = value;
	}

	return { data, body };
}

/** 转义 SQL 字符串（防注入） */
function esc(str) {
	if (typeof str === "boolean") return str ? 1 : 0;
	if (typeof str !== "string") return str;
	return `'${str.replace(/'/g, "''")}'`;
}

/** 用 slug 生成稳定的 UUID */
function stableId(prefix, slug) {
	return (
		prefix +
		"_" +
		crypto.createHash("md5").update(slug).digest("hex").substring(0, 8)
	);
}

// ===== 主流程 =====
const sqlLines = [];

function collectFiles(dir, baseDir) {
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	const files = [];

	for (const entry of entries) {
		if (entry.name.startsWith(".")) continue;
		const fullPath = path.join(dir, entry.name);

		if (entry.isDirectory()) {
			files.push(...collectFiles(fullPath, baseDir));
		} else if (entry.name.endsWith(".md")) {
			files.push(fullPath);
		}
	}

	return files;
}

const mdFiles = collectFiles(POSTS_DIR, POSTS_DIR);

console.error(`Found ${mdFiles.length} .md files`);

for (const filePath of mdFiles) {
	const content = fs.readFileSync(filePath, "utf-8");
	const { data, body } = parseFrontmatter(content);

	const relativePath = path.relative(POSTS_DIR, filePath);
	// slug: en/xxx → "en/xxx" (glob loader ID 格式)
	// 普通文件: xxx → "xxx"
	const slug = relativePath.replace(/\.md$/, "").replace(/\\/g, "/");

	// 生成 ID
	const id = stableId("cnt", slug);

	const published =
		data.published || data.date || new Date().toISOString().split("T")[0];

	// 构建 custom_data JSON
	const customData = {};
	if (data.tags && Array.isArray(data.tags)) customData.tags = data.tags;
	if (data.description) customData.description = data.description;
	if (data.lang) customData.lang = data.lang;
	if (data.pinned !== undefined) customData.pinned = data.pinned;
	if (data.translationKey) customData.translationKey = data.translationKey;
	if (data.updated) customData.updated = data.updated;

	// 保留 notionSync/notionPageId（如果有）
	if (data.notionSync) customData.notionSync = data.notionSync;
	if (data.notionPageId) customData.notionPageId = data.notionPageId;

	const status = data.draft ? "draft" : "published";

	const sql = `INSERT INTO tenon_contents (id, module_id, title, slug, date, status, cover, body_md, custom_data) VALUES (${esc(id)}, ${esc(MODULE_ID)}, ${esc(data.title || "Untitled")}, ${esc(slug)}, ${esc(published)}, ${esc(status)}, ${esc(data.image || data.cover || "")}, ${esc(body)}, ${esc(JSON.stringify(customData))});`;

	sqlLines.push(sql);
	console.error(`  ${slug} → ${id} (${status})`);
}

// 输出
console.log("-- Auto-generated by scripts/import-to-d1.js");
console.log("-- import " + mdFiles.length + " posts into tenon_contents\n");
sqlLines.forEach((line) => console.log(line));

console.error(
	`\nDone. ${sqlLines.length} INSERT statements generated.`,
);
console.error("Run: npx wrangler d1 execute tenon-db --remote --file=import.sql");
